---
volumes:
  caddy_data: {}

networks:
  caddy:
    name: caddy
    driver: bridge

services:
  caddy:
    image: mafrosis/caddy
    build:
      context: .
      args:
        CADDY_DOCKER_TAG: ${CADDY_DOCKER_TAG}
        CADDY_DOCKER_PROXY_PLUGIN: ${CADDY_DOCKER_PROXY_PLUGIN}
        CADDY_GANDI_PLUGIN: ${CADDY_GANDI_PLUGIN}
    restart: unless-stopped
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    env_file:
      - .secrets
    ports:
      - 443:443
      - 2020:2020
    networks:
      - caddy
    extra_hosts:
      - ca.mafro.net:192.168.1.198  # Caddy needs to reach internal CA
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
      - $HOME/.step/certs/root_ca.crt:/root/step_ca.crt:ro  # Referenced by containers using the proxy
      - $HOME/.step/certs/root_ca.crt:/etc/ssl/certs/step_ca.crt:ro  # Local trust for Step CA
    labels:
      caddy.email: dev@mafro.net
      caddy.log.format: console  # Human readable, not JSON
      #caddy.log.level: debug
