---
volumes:
  caddy-data: {}
  tailscale-data: {}

networks:
  caddy:
    name: caddy
    driver: bridge

services:
  caddy:
    image: mafrosis/caddy:${CADDY_DOCKER_TAG}
    build:
      context: .
      target: ${BUILD_TARGET:-caddy}
      args:
        CADDY_DOCKER_TAG: ${CADDY_DOCKER_TAG}
        CADDY_DOCKER_PROXY_PLUGIN: ${CADDY_DOCKER_PROXY_PLUGIN}
        CADDY_GANDI_PLUGIN: ${CADDY_GANDI_PLUGIN}
        HOSTNAME: ${HOSTNAME}
    restart: unless-stopped
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
      - TS_AUTHKEY
    env_file:
      - .secrets
    ports:
      - 443:443
    networks:
      - caddy
    extra_hosts:
      ca.mafro.net: 192.168.1.198  # Caddy needs to reach internal CA
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy-data:/data
      - tailscale-data:/ts
      - /etc/step_root_ca.crt:/root/step_ca.crt:ro  # Referenced by containers using the proxy
      - /etc/step_root_ca.crt:/etc/ssl/certs/step_ca.crt:ro  # Local trust for Step CA
    labels:
      caddy.email: dev@mafro.net
      caddy.log.format: console  # Human readable, not JSON
      #caddy.log.level: debug
